markdown: kramdown
highlights: pygments
incremental: true
regenerate: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
safe: true
timezone: Asia/Shanghai
url:

# Markdown 处理器
#kramdown:
#  auto_ids: true,
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  use_coderay: false


domain: http://zhangxl.me
title: xlbengle|blog
author: zhangxl
email: acc110789@sina.com
github: acc110789

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
