markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
#incremental: true
#regenerate: true
#safe: true
timezone: Asia/Shanghai
url:
title: xlbengle|blog

domain: http://zhangxl.me
title: xlbengle|blog
author: zhangxl
email: acc110789@sina.com
github: acc110789

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
